baseURL = "/"
languageCode = "en-us"
title = "Resume | Marcos Izaguirre"
disableKinds = ["taxonomy", "term", "page", "section", "RSS", "sitemap", "robotsTXT", "404"]
theme = "resume-A4"

[params]
useFontAwesome = true
avatar = "avatar.jpg"
bib_style = "IEEE" # IEEE, APA, else

[params.display]
experience = true
education = true
languages = true
awards = false
skills = false
skills_grouped = true
interests = true
contact = false
linkedin = false
tagline = true
aboutMe = true
projects = true
publications = false
certificates = false
avatar = false

[params.title_as]
experience = "Coding Experience"
education = "Education"
languages = "Languages"
awards = "Awards"
skills = "Skills"
certificates = "Certifications"
interests = "Interests"
about_me = "About Me"
publications = "Publications"
projects = "Projects"

[params.display.footer]
footer = true
links = true
credits = true

[params.footer]
footnote = "You can print this resume in A4 size or save as pdf. | Last update on 01.09.2020."

[params.footer.links]
[[params.footer.links.link]]
prefix = "Contact me on"
name = "Linkedin"
url = "https://linkedin.com/in/mertbakir/"
icon = "fab fa-linkedin"

[[params.footer.links.link]]
prefix = "Check out my"
name = "Website"
url = "https://mertbakir.gitlab.io/about/"
icon = "fas fa-globe"